### ISSUE TITLE
Borrow the good parts from dynsampler-go readme

### ISSUE THREAD

**Issue by eanakashima** [honeycombio/dynsampler-js#2]
The [dynsampler-go readme](https://github.com/honeycombio/dynsampler-go/blob/master/README.md) has some short but useful explanations of what a sample rate is and when the different available sampling methods may be helpful. Could we adapt the relevant bits for this repo too?

**Comment by ChristopherBiscardi** [comment]
done in 6e04e70b6b382ed0a5d2fe792cb99eab014e372c
