### ISSUE TITLE
Document usage in a browser environment

### ISSUE THREAD

**Issue by eanakashima** [honeycombio/dynsampler-js#3]
It would be handy to have the readme cover:

- whether this project is suitable for use in browser js
- whether it depends on any newish browser APIS (and/or needs to be transpiled with babel)

**Comment by ChristopherBiscardi** [comment]
It's precompiled using buble, so that should result in most ES2015 being compiled out without a runtime and should document that we offer commonjs, umd, .m.js, and source versions in the final package (via microbundle)

**Comment by vreynolds** [comment]
Project is being sunset: https://github.com/honeycombio/dynsampler-js/issues/32
